// GENERATED FILE — DO NOT EDIT
//
// This file is generated from `data/known_semantics_v2.6.json` and contains
// the compiled `rawKnownSemanticsV26` map used by `KnownSemanticsRepository`.
// If you need to update widget metadata, modify the JSON source and run the
// generator (not present in this repo yet). Prefer creating `tool/generate_*`
// scripts to produce this file rather than hand-editing it.
//
// The generator should ensure the output is deterministic and includes the
// same keys/fields expected by `known_semantics.dart`.
const Map<String, Map<String, Object>> rawKnownSemanticsV26 = {
  'Scaffold': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': true,
    'slotTraversalOrder': [
      'appBar',
      'body',
      'floatingActionButton',
      'bottomSheet',
      'bottomNavigationBar',
      'drawer',
      'endDrawer',
    ],
  },
  'AppBar': {
    'role': 'header',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['leading', 'title', 'actions', 'bottom'],
  },
  'Card': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': true,
    'slotTraversalOrder': ['child'],
  },
  'ListTile': {
    'role': 'unknown',
    'controlKind': 'listTile',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['leading', 'title', 'subtitle', 'trailing'],
    'schema': {
      'label': [
        {'type': 'slot', 'slotName': 'title'},
      ],
    },
  },
  'ElevatedButton': {
    'role': 'button',
    'controlKind': 'elevatedButton',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child', 'icon', 'label'],
  },
  'TextButton': {
    'role': 'button',
    'controlKind': 'textButton',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child', 'icon', 'label'],
  },
  'FilledButton': {
    'role': 'button',
    'controlKind': 'filledButton',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child', 'icon', 'label'],
  },
  'OutlinedButton': {
    'role': 'button',
    'controlKind': 'outlinedButton',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child', 'icon', 'label'],
  },
  'IconButton': {
    'role': 'button',
    'controlKind': 'iconButton',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': true,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['icon'],
    'schema': {
      'label': [
        {'type': 'prop', 'name': 'tooltip', 'sourceOverride': 'tooltip'},
      ],
      'tooltip': [
        {'type': 'prop', 'name': 'tooltip'},
      ],
    },
  },
  'FloatingActionButton': {
    'role': 'button',
    'controlKind': 'floatingActionButton',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': true,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child', 'icon', 'label'],
    'schema': {
      'label': [
        {'type': 'prop', 'name': 'tooltip', 'sourceOverride': 'tooltip'},
      ],
      'tooltip': [
        {'type': 'prop', 'name': 'tooltip'},
      ],
    },
  },
  'Checkbox': {
    'role': 'checkbox',
    'controlKind': 'checkboxControl',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': true,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
    'schema': {
      'isChecked': [
        {'type': 'prop', 'name': 'value'},
      ],
    },
  },
  'Switch': {
    'role': 'switchRole',
    'controlKind': 'switchControl',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': true,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
    'schema': {
      'toggled': [
        {'type': 'prop', 'name': 'value'},
      ],
    },
  },
  'Slider': {
    'role': 'slider',
    'controlKind': 'sliderControl',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': true,
    'hasDecrease': true,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
  },
  'TextField': {
    'role': 'textField',
    'controlKind': 'textFieldControl',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': true,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
  },
  'Text': {
    'role': 'staticText',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
    'schema': {
      'label': [
        {'type': 'positional', 'index': 0, 'sourceOverride': 'textChild'},
        {'type': 'prop', 'name': 'data', 'sourceOverride': 'textChild'},
      ],
    },
  },
  'RichText': {
    'role': 'staticText',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
  },
  'Image': {
    'role': 'image',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
  },
  'Icon': {
    'role': 'unknown',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': [],
    'schema': {
      'label': [
        {'type': 'prop', 'name': 'semanticLabel'},
      ],
    },
  },
  'Column': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': true,
    'slotTraversalOrder': ['children'],
  },
  'Row': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': true,
    'slotTraversalOrder': ['children'],
  },
  'Stack': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': true,
    'slotTraversalOrder': ['children'],
  },
  'Container': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': true,
    'slotTraversalOrder': ['child'],
  },
  'Semantics': {
    'role': 'unknown',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
  'MergeSemantics': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
  'ExcludeSemantics': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': true,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
  'BlockSemantics': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': true,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
  'IndexedSemantics': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
  'GestureDetector': {
    'role': 'group',
    'controlKind': 'none',
    'isFocusable': false,
    'isEnabledByDefault': true,
    'hasTap': false,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': false,
    'implicitlyMergesSemantics': false,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
  'InkWell': {
    'role': 'button',
    'controlKind': 'none',
    'isFocusable': true,
    'isEnabledByDefault': true,
    'hasTap': true,
    'hasLongPress': false,
    'hasIncrease': false,
    'hasDecrease': false,
    'isToggled': false,
    'isChecked': false,
    'mergesDescendants': true,
    'implicitlyMergesSemantics': true,
    'excludesDescendants': false,
    'blocksBehind': false,
    'isPureContainer': false,
    'slotTraversalOrder': ['child'],
  },
};
