// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/semantics_generator/generate_source.dart
// From runtime Flutter semantics extraction
//
// To regenerate:
//   1. flutter test test/semantics_generator/extract_semantics_test.dart
//   2. dart tool/semantics_generator/generate_source.dart

import '../types/semantic_role.dart';
import 'widget_semantics_info.dart';

/// Pre-built semantic information for Flutter built-in widgets
class KnownWidgetSemantics {
  /// Map of widget names to their semantic information
  static const Map<String, WidgetSemanticsInfo> widgets = {
    'IconButton': WidgetSemanticsInfo(
      role: SemanticRole.button,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: true,
      hasSemanticLabelParam: false,
    ),
    'ElevatedButton': WidgetSemanticsInfo(
      role: SemanticRole.button,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'TextButton': WidgetSemanticsInfo(
      role: SemanticRole.button,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'OutlinedButton': WidgetSemanticsInfo(
      role: SemanticRole.button,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'FilledButton': WidgetSemanticsInfo(
      role: SemanticRole.button,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'FloatingActionButton': WidgetSemanticsInfo(
      role: SemanticRole.button,
      isInteractive: true,
      mergesChildren: true,
      semanticsManaged: true,
      hasTooltipParam: true,
      hasSemanticLabelParam: false,
    ),
    'Switch': WidgetSemanticsInfo(
      role: SemanticRole.toggle,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Checkbox': WidgetSemanticsInfo(
      role: SemanticRole.toggle,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Radio': WidgetSemanticsInfo(
      role: SemanticRole.toggle,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'SwitchListTile': WidgetSemanticsInfo(
      role: SemanticRole.toggle,
      isInteractive: true,
      mergesChildren: true,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'CheckboxListTile': WidgetSemanticsInfo(
      role: SemanticRole.toggle,
      isInteractive: true,
      mergesChildren: true,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'RadioListTile': WidgetSemanticsInfo(
      role: SemanticRole.toggle,
      isInteractive: true,
      mergesChildren: true,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'TextField': WidgetSemanticsInfo(
      role: SemanticRole.input,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'TextFormField': WidgetSemanticsInfo(
      role: SemanticRole.input,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Slider': WidgetSemanticsInfo(
      role: SemanticRole.slider,
      isInteractive: true,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'ListTile': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: true,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Card': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: true,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Image': WidgetSemanticsInfo(
      role: SemanticRole.image,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: true,
    ),
    'Icon': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'CircleAvatar': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: true,
    ),
    'Text': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Semantics': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'MergeSemantics': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: true,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'ExcludeSemantics': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'BlockSemantics': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: true,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Row': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Column': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
    'Wrap': WidgetSemanticsInfo(
      role: SemanticRole.group,
      isInteractive: false,
      mergesChildren: false,
      semanticsManaged: false,
      hasTooltipParam: false,
      hasSemanticLabelParam: false,
    ),
  };

  /// Lookup semantics info for a widget by name
  static WidgetSemanticsInfo? lookup(String? widgetName) {
    if (widgetName == null) return null;
    return widgets[widgetName];
  }
}
