// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart

import '../src/query/faql4.dart';

/// Validated FAQL 4 Core built-in queries.
final List<CompiledQuery> builtinFaqlRules = List.unmodifiable([
  Faql4Compiler().compile(r'''@id flutter-a11y/a01/unlabeled-interactive
@rule-id a01_unlabeled_interactive
@severity warning
@mode conservative
from InteractiveControl control
where control.isDefinitelyExposed() and
  control.isDefinitelyEnabled() and
  control.isDefinitelyUnlabeled()
select control, "Interactive control must have an accessible label."
'''), // flutter-a11y/a01/unlabeled-interactive
  Faql4Compiler().compile(r'''@id flutter-a11y/a02/avoid-redundant-role-words
@rule-id a02_avoid_redundant_role_words
@severity warning
@mode expanded
from InteractiveControl control
where (control.hasStaticNameFrom("tooltip") or
  control.hasStaticNameFrom("semanticsLabel") or
  control.hasStaticNameFrom("widgetLabel") or
  control.hasStaticNameFrom("inputDecoration") or
  control.hasStaticNameFrom("customWidgetDerived") or
  control.hasStaticNameFrom("frameworkDerived")) and
  control.hasStaticNameMatching("(^|[^a-z])(button|btn|icon|image|link|checkbox|radio|switch|selected|checked|toggle)($|[^a-z])", false)
select control, "Accessible names should not repeat their semantic role."
'''), // flutter-a11y/a02/avoid-redundant-role-words
  Faql4Compiler().compile(r'''@id flutter-a11y/a03/decorative-images-excluded
@rule-id a03_decorative_images_excluded
@severity warning
@mode expanded
from ImageNode image
where image.isKnownDecorativeAsset() and
  image.isDefinitelyUnlabeled() and
  image.isDefinitelyNotExcludedFromSemantics()
select image, "Exclude purely decorative images from semantics."
'''), // flutter-a11y/a03/decorative-images-excluded
  Faql4Compiler().compile(r'''@id flutter-a11y/a04/list-tile-image-labeled
@rule-id a04_informative_images_labeled
@severity warning
@mode conservative
from ImageNode image
where image.isDefinitelyIncludedInSemantics() and
  image.isNetworkOrFileImage() and
  image.isDefinitelyNotExcludedFromSemantics() and
  image.isDefinitelyEffectivelyUnlabeled() and
  exists(ListTileNode tile | image = tile.getSlot("leading"))
select image, "Informative ListTile leading images must provide semantic labels."
'''), // flutter-a11y/a04/list-tile-image-labeled
  Faql4Compiler().compile(r'''@id flutter-a11y/a05/redundant-button-semantics
@rule-id a05_no_redundant_button_semantics
@severity warning
@mode expanded
from SemanticsNode wrapper
where wrapper.hasExplicitSemanticsButtonRole() and
  wrapper.hasNoMeaningfulSemanticsConfiguration() and
  exists(MaterialButtonControl button | button = wrapper.getAChild())
select wrapper, "Remove the role-only Semantics wrapper around the button."
'''), // flutter-a11y/a05/redundant-button-semantics
  Faql4Compiler().compile(r'''@id flutter-a11y/a09/numeric-names-require-units
@rule-id a09_numeric_values_require_units
@severity warning
@mode expanded
from SemanticNode node
where node.hasStaticNameMatching("^[ ]*[0-9]+([.][0-9]+)?[ ]*$")
select node, "Numeric accessible names should include meaningful units."
'''), // flutter-a11y/a09/numeric-names-require-units
  Faql4Compiler().compile(r'''@id flutter-a11y/a15/label-custom-gesture-actions
@rule-id a15_map_custom_gestures_to_on_tap
@severity warning
@mode expanded
from InteractiveControl control
where control.getWidgetType() = "GestureDetector" and
  control.hasTapAction() and
  control.isDefinitelyUnlabeled()
select control, "Custom gesture actions should provide an accessible name."
'''), // flutter-a11y/a15/label-custom-gesture-actions
  Faql4Compiler()
      .compile(r'''@id flutter-a11y/a22/respect-widget-semantic-boundaries
@rule-id a22_respect_widget_semantic_boundaries
@severity warning
@mode conservative
from MergeSemanticsNode merge
where merge.isDefinitelyExposed() and
  exists(ListTileNode tile | tile = merge.getAChild())
select merge, "ListTile family widgets already merge semantics; remove the MergeSemantics wrapper."
'''), // flutter-a11y/a22/respect-widget-semantic-boundaries
  Faql4Compiler().compile(r'''@id flutter-a11y/merge/multiple-actions
@rule-id merge_multiple_actions
@severity warning
@mode conservative
from MergeSemanticsNode merge
where merge.isDefinitelyExposed() and
  count(InteractiveControl control |
  control = merge.getADescendant() and control.isDefinitelyEnabled()) >= 2
select merge, "Merged semantics contain multiple independently actionable controls."
'''), // flutter-a11y/merge/multiple-actions
]);
