// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart

import '../src/query/faql4.dart';

/// Validated FAQL 4 Core built-in queries.
final List<CompiledQuery> builtinFaqlRules = List.unmodifiable([
  Faql4Compiler().compile(r'''@id flutter-a11y/a01/unlabeled-interactive
@rule-id a01_unlabeled_interactive
@severity warning
@mode conservative
from InteractiveControl control
where control.isDefinitelyEnabled() and control.isDefinitelyUnlabeled()
select control, "Interactive control must have an accessible label."
'''), // flutter-a11y/a01/unlabeled-interactive
  Faql4Compiler().compile(r'''@id flutter-a11y/a04/list-tile-image-labeled
@rule-id a04_informative_images_labeled
@severity warning
@mode conservative
from ImageNode image
where image.isNetworkOrFileImage() and
  image.isDefinitelyNotExcludedFromSemantics() and
  image.isDefinitelyEffectivelyUnlabeled() and
  exists(ListTileNode tile | image = tile.getSlot("leading"))
select image, "Informative ListTile leading images must provide semantic labels."
'''), // flutter-a11y/a04/list-tile-image-labeled
  Faql4Compiler()
      .compile(r'''@id flutter-a11y/a22/respect-widget-semantic-boundaries
@rule-id a22_respect_widget_semantic_boundaries
@severity warning
@mode conservative
from MergeSemanticsNode merge
where exists(ListTileNode tile | tile = merge.getAChild())
select merge, "ListTile family widgets already merge semantics; remove the MergeSemantics wrapper."
'''), // flutter-a11y/a22/respect-widget-semantic-boundaries
]);
