// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart

import '../src/query/faql4.dart';

/// Validated FAQL 4 Core built-in queries.
final List<CompiledQuery> builtinFaqlRules = List.unmodifiable([
  Faql4Compiler().compile(r'''@id flutter-a11y/a01/unlabeled-interactive
@rule-id a01_unlabeled_interactive
@severity warning
@mode conservative
from InteractiveControl control
where control.isDefinitelyEnabled() and control.isDefinitelyUnlabeled()
select control, "Interactive control must have an accessible label."
'''), // flutter-a11y/a01/unlabeled-interactive
  Faql4Compiler().compile(r'''@id flutter-a11y/a03/decorative-images-excluded
@rule-id a03_decorative_images_excluded
@severity warning
@mode conservative
from ImageNode image
where image.isKnownDecorativeAsset() and image.isDefinitelyUnlabeled() and image.isDefinitelyNotExcludedFromSemantics()
select image, "Exclude purely decorative images from semantics."
'''), // flutter-a11y/a03/decorative-images-excluded
  Faql4Compiler().compile(r'''@id flutter-a11y/a04/circle-avatar-labeled
@rule-id a04_informative_images_labeled
@severity warning
@mode conservative
from ImageNode image
where image.getWidgetType() = "CircleAvatar" and image.hasImageContent() and image.isDefinitelyUnlabeled()
select image, "Informative images must provide semantic labels."
'''), // flutter-a11y/a04/circle-avatar-labeled
  Faql4Compiler().compile(r'''@id flutter-a11y/a04/list-tile-image-labeled
@rule-id a04_informative_images_labeled
@severity warning
@mode conservative
from ImageNode image
where image.isNetworkOrFileImage() and image.isDefinitelyUnlabeled() and exists(ListTileNode ancestor | ancestor = image.getAnAncestor())
select image, "Informative images must provide semantic labels."
'''), // flutter-a11y/a04/list-tile-image-labeled
]);
