import 'dart:io';

/// Small helper to generate a version constant file from pubspec.yaml.
/// This allows the CLI to report the package version used by the project
/// without duplicating the value manually.
///
/// Usage: dart run tool/generate_version.dart
void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('Error: pubspec.yaml not found.');
    exit(1);
  }
  final content = pubspec.readAsStringSync();
  // Allow leading whitespace and stop at whitespace or comment after the version
  final versionMatch =
      RegExp(r'^\s*version:\s*([^\s#]+)', multiLine: true).firstMatch(content);
  if (versionMatch == null) {
    stderr.writeln('Error: version not found in pubspec.yaml');
    exit(1);
  }
  var version = versionMatch.group(1)!.trim();
  // strip quotes if any
  version = version.replaceAll('"', '').replaceAll("'", '');

  final outFile = File('lib/src/version.g.dart');
  if (!outFile.parent.existsSync()) outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync('// GENERATED FILE - DO NOT MODIFY\n'
      '// Generated by tool/generate_version.dart\n\n'
      "const String kPackageVersion = '$version';\n");
  print('Wrote version $version to ${outFile.path}');
}
