import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:flutter_a11y_lints/src/query/faql4.dart';

/// Script to embed .faql rules into a Dart file for the CLI.
/// Usage: dart run tool/generate_rules.dart
void main() async {
  // 1. Define paths
  final rulesDir = Directory(p.join('lib', 'rules', 'core'));
  final outputFile = File(p.join('lib', 'rules', 'builtin_faql_rules.g.dart'));

  if (!rulesDir.existsSync()) {
    print('Error: Rules directory not found at ${rulesDir.path}');
    print('Please create "lib/rules" and add your .faql files there.');
    exit(1);
  }

  print('Generating built-in rules from ${rulesDir.path}...');

  final buffer = StringBuffer();

  // 2. Write Header
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_rules.dart');
  buffer.writeln();
  buffer.writeln("import '../src/query/faql4.dart';");
  buffer.writeln();
  buffer.writeln('/// Validated FAQL 4 Core built-in queries.');
  buffer.writeln(
      'final List<CompiledQuery> builtinFaqlRules = List.unmodifiable([');

  // 3. Scan and Embed Files
  final files = rulesDir.listSync().whereType<File>().toList();
  // Sort for deterministic output
  files.sort((a, b) => a.path.compareTo(b.path));

  var count = 0;
  for (final file in files) {
    if (!file.path.endsWith('.faql')) continue;

    final filename = p.basename(file.path);
    final content = await file.readAsString();
    final query = Faql4Compiler().compile(content);

    // Sanitize content for raw string literal
    // We use r''' ... ''' so we only need to escape triple quotes if they exist
    final safeContent = content.replaceAll("'''", r"\'\'\'");

    buffer.writeln(
        "  Faql4Compiler().compile(r'''$safeContent'''), // ${query.queryId}");
    count++;
    print('  Included: $filename');
  }

  // 4. Write Footer
  buffer.writeln(']);');

  // 5. Save to disk
  if (!outputFile.parent.existsSync()) {
    outputFile.parent.createSync(recursive: true);
  }

  await outputFile.writeAsString(buffer.toString());

  print('----------------------------------------------------------------');
  print('Success! Embedded $count rules into ${outputFile.path}');
  print('You can now run "dart bin/main.dart" without file system errors.');
}
