import 'dart:io';
import 'package:path/path.dart' as p;

/// Script to embed .faql rules into a Dart file for the CLI.
/// Usage: dart run tool/generate_rules.dart
void main() async {
  // 1. Define paths
  final rulesDir = Directory(p.join('lib', 'rules'));
  final outputFile =
      File(p.join('lib', 'src', 'rules', 'builtin_faql_rules.g.dart'));

  if (!rulesDir.existsSync()) {
    print('Error: Rules directory not found at ${rulesDir.path}');
    print('Please create "lib/rules" and add your .faql files there.');
    exit(1);
  }

  print('Generating built-in rules from ${rulesDir.path}...');

  final buffer = StringBuffer();

  // 2. Write Header
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_rules.dart');
  buffer.writeln();
  buffer.writeln('/// Map of filename/code to FAQL rule source content.');
  buffer.writeln('const Map<String, String> builtinFaqlRules = {');

  // 3. Scan and Embed Files
  final files = rulesDir.listSync().whereType<File>().toList();
  // Sort for deterministic output
  files.sort((a, b) => a.path.compareTo(b.path));

  var count = 0;
  for (final file in files) {
    if (!file.path.endsWith('.faql')) continue;

    final filename = p.basename(file.path);
    // Using filename as key for uniqueness
    final key = filename;

    final content = await file.readAsString();

    // Sanitize content for raw string literal
    // We use r''' ... ''' so we only need to escape triple quotes if they exist
    final safeContent = content.replaceAll("'''", r"\'\'\'");

    buffer.writeln("  '$key': r'''$safeContent''',");
    count++;
    print('  Included: $filename');
  }

  // 4. Write Footer
  buffer.writeln('};');

  // 5. Save to disk
  if (!outputFile.parent.existsSync()) {
    outputFile.parent.createSync(recursive: true);
  }

  await outputFile.writeAsString(buffer.toString());

  print('----------------------------------------------------------------');
  print('Success! Embedded $count rules into ${outputFile.path}');
  print('You can now run "dart bin/main.dart" without file system errors.');
}
